<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NavigationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('navigation')->insert([
            [
                'id' => 1,
                'sort_order' => 10,
                'name_en' => 'Home',
                'name_es' => 'Inicio',
                'path' => '/',
                'component_name' => 'HomePage',
                'source' => 'home',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'sort_order' => 20,
                'name_en' => 'Shelter Project',
                'name_es' => 'Proyecto de Refugio',
                'path' => '/shelter-project',
                'component_name' => 'ShelterProject',
                'source' => 'shelter-project',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'sort_order' => 32,
                'name_en' => 'Upcoming',
                'name_es' => 'Próximos',
                'path' => '/events/upcoming-events',
                'component_name' => 'EventsPage',
                'source' => 'faan-events',
                'visible' => true,
                'parent_id' => 13,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'sort_order' => 40,
                'name_en' => 'Adoptions',
                'name_es' => 'Adopciones',
                'path' => '/adoptions',
                'component_name' => 'AdoptionsPage',
                'source' => 'adoptions',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'sort_order' => 50,
                'name_en' => 'Donations',
                'name_es' => 'Donaciones',
                'path' => '/donations',
                'component_name' => 'DonationsPage',
                'source' => 'donations',
                'visible' => true,
                'parent_id' => 12,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'sort_order' => 60,
                'name_en' => 'Legacy Giving',
                'name_es' => 'Donación de Legado',
                'path' => '/legacy-giving',
                'component_name' => 'LegacyGiving',
                'source' => 'legacy-giving',
                'visible' => true,
                'parent_id' => 12,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'sort_order' => 70,
                'name_en' => 'Volunteering',
                'name_es' => 'Trabajar como Voluntario',
                'path' => '/volunteering',
                'component_name' => 'VolunteeringPage',
                'source' => 'volunteering',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'sort_order' => 80,
                'name_en' => 'Media/Resources',
                'name_es' => 'Medios/Recursos',
                'path' => '/media-resources',
                'component_name' => 'MediaResources',
                'source' => 'media-resources',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'sort_order' => 100,
                'name_en' => 'GALA-FAANTASTICA',
                'name_es' => 'GALA-FAANTASTICA',
                'path' => 'https://gala-{{language}}.castoware.com',
                'component_name' => 'GalaFaantastica',
                'source' => 'gala-faantastica',
                'visible' => true,
                'parent_id' => 0,
                'external' => true,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'sort_order' => 110,
                'name_en' => 'Contact Us',
                'name_es' => 'Contáctenos',
                'path' => '/contact-us',
                'component_name' => 'ContactUs',
                'source' => 'contact-us',
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'sort_order' => 45,
                'name_en' => 'Donate',
                'name_es' => 'Donar',
                'path' => null,
                'component_name' => null,
                'source' => null,
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'sort_order' => 30,
                'name_en' => 'FAAN Events',
                'name_es' => 'Eventos FAAN',
                'path' => null,
                'component_name' => null,
                'source' => null,
                'visible' => true,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'sort_order' => 35,
                'name_en' => 'Past',
                'name_es' => 'Pasados',
                'path' => '/events/past-events',
                'component_name' => 'EventsPage',
                'source' => 'faan-events',
                'visible' => true,
                'parent_id' => 13,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'sort_order' => 90,
                'name_en' => 'FAAN Holiday Store',
                'name_es' => 'Tienda Navideña FAAN',
                'path' => 'https://gala-{{language}}.castoware.com/buy-now',
                'component_name' => 'FaanHolidayStorey',
                'source' => 'faan-holiday-store',
                'visible' => false,
                'parent_id' => 0,
                'external' => true,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'sort_order' => 120,
                'name_en' => 'FAAN-atics Volunteer Slide Show',
                'name_es' => 'Presentación de diapositivas de voluntarios de FAAN-atics',
                'path' => '/faan-atics-volunteer-slide-show',
                'component_name' => 'FaanaticsSlideShow',
                'source' => 'faan-atics-slide-show',
                'visible' => false,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'sort_order' => 130,
                'name_en' => 'View PDF',
                'name_es' => 'Ver PDF',
                'path' => '/view-pdf',
                'component_name' => 'ViewPdf',
                'source' => 'view-pdf',
                'visible' => false,
                'parent_id' => 0,
                'external' => false,
                'external_blank' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
